### PR TITLE
Fixes blurry scaled-down covers on the ballot

### LINKED ISSUE #165: The scaled-down cover images are blurry
On a high-resolution ("retina") display, the scaled-down cover images look significantly blurrier than they would if the original images were displayed with browser-based scale-down.

I suspect that the solution is as simple as doubling the $MAX_COVER_HEIGHT variable defined in IFComp::Controller::Entry.

### PR DESCRIPTION
**Pull request by jmacdotorg**
I was correct on #165: This just took the adjustment of a single number.

It will also require running a script to re-process covers already uploaded this year, which is attached to this PR.

Fixes #165.

### CODE REVIEW

File: IFComp/lib/IFComp/Controller/Entry.pm [hunk 1]
```diff
@@ -302,16 +300,7 @@ sub _process_form {
                     # scaled-down web copy.
                     $entry->web_cover_file->remove;
                     $entry->clear_web_cover_file;
```
Comment (adherzog) [inline IFComp/lib/IFComp/Controller/Entry.pm:302]: Shouldn't these lines be moved into `$entry->create_web_cover_file()` too?

File: IFComp/script/README.md [hunk 2]
```diff
@@ -12,6 +12,7 @@ may be found within the script itself.
  * `delete_unfulfilled_intents.pl` - This script marks every entry without a main file as disqualified. Useful for marking unfulfilled intents, post-deadline.
  * `populate_ifdb_ids.pl` - This script does its best to update the IFDB ID field for every game in the current year's comp.
  * `rebuild_entry_content_dirs` - This script rebuilds the 'content' directory for every entry. Useful if you change what's stored in those directories while a comp is underway.
+ * `resize_web_covers.pl` - Re-processes all the current comp's entries' covers, creating scaled-down versions for use by the ballot webpage. Useful if we wish to change the maximum image size displayed by the ballot.
```
Comment (adherzog) [inline IFComp/script/README.md:15]: Please update with the new script name.

File: IFComp/script/recreate_web_covers.pl [hunk 3]
```diff
@@ -0,0 +1,21 @@
+use warnings;
+use strict;
+
+use v5.10;
+
+use FindBin;
+use Imager;
```
Comment (adherzog) [inline IFComp/script/recreate_web_covers.pl:7]: No longer need Imager in here.
